// Generates supabase/seed.sql from the TypeScript registry, so the database and
// the app never disagree about which languages exist.
//   node scripts/generate-seed.ts
import { writeFileSync } from "node:fs";
import { families, languages } from "../data/languages/registry.ts";
import { counties } from "../data/seed/counties.ts";

const q = (v: string | number | boolean | undefined | null) =>
  v === undefined || v === null ? "null" : typeof v === "string" ? `'${v.replace(/'/g, "''")}'` : String(v);
const slug = (name: string) => name.toLowerCase().replace(/[^a-z]+/g, "-");

const lines = [
  "-- Generated by scripts/generate-seed.ts. Do not edit by hand.",
  "",
  ...families.map((f) => `insert into language_families (id, name, description) values (${q(f.id)}, ${q(f.name)}, ${q(f.description)}) on conflict (id) do nothing;`),
  "",
  ...counties.map((c) => `insert into regions (id, name, kind) values (${q(slug(c))}, ${q(c)}, 'county') on conflict (id) do nothing;`),
  "",
  // Parents first, so parent_id foreign keys resolve.
  ...[...languages]
    .sort((a, b) => Number(Boolean(a.parentId)) - Number(Boolean(b.parentId)))
    .map(
      (l) =>
        `insert into languages (id, name, native_name, iso639_3, family_id, status, coverage, is_focus, is_cluster, parent_id, description, verified) values (${[
          l.id, l.name, l.nativeName, l.iso639_3, l.family, l.status, l.coverage, Boolean(l.isFocus), Boolean(l.isCluster), l.parentId, l.description, l.verified,
        ].map(q).join(", ")}) on conflict (id) do nothing;`,
    ),
  "",
];
writeFileSync(new URL("../supabase/seed.sql", import.meta.url), lines.join("\n"));
console.log(`seed.sql: ${families.length} families, ${counties.length} counties, ${languages.length} languages`);
